#!/bin/bash
set -e

usage () {
    echo "USAGE: mapscript-to-env path-to-env-python path-to-main-python"
    exit -1
}

if [ -z $2 ]; then usage; fi

SRC=`$2 -c "from __future__ import print_function; import mapscript, os.path; print(os.path.split(mapscript.__file__)[0])"`
DST=`$1 -c "from __future__ import print_function; import sys; print(sys.path[-1])"`

cp -vu $SRC/mapscript.py $DST

if [[ -f $SRC/_mapscript.so ]]; then
    cp -vu $SRC/_mapscript.so $DST
elif [[ -f $SRC/_mapscript.x86_64-linux-gnu.so ]]; then
    cp -vu $SRC/_mapscript.x86_64-linux-gnu.so $DST
elif [[ -f $SRC/_mapscript.cpython-36m-x86_64-linux-gnu.so ]]; then
    cp -vu $SRC/_mapscript.cpython-36m-x86_64-linux-gnu.so $DST
else
    echo "Cannot find mapscript library file!"
    exit 1
fi
